# Generated by Django 5.2.5 on 2025-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Gmail app password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails', max_length=254, null=True),
        ),
    ]
